### ISSUE TITLE
Register typings

### ISSUE THREAD

**Issue by paullryan** [stevemao/gulp-conventional-changelog#2]
I suggest a typings gets registered for this project. I've created a basic version at https://github.com/paullryan/gulp-conventional-changelog-typings (this is functional) but don't believe I've covered all the options. Please review and either take over or suggest changes. Then we can register with https://github.com/typings/registry.

**Comment by stevemao** [comment]
We must have a wrapper module for typings? Can we register with this one directly? Otherwise all my modules need a dummy wrapper and it's not realistic.

**Comment by paullryan** [comment]
Any user of typings can create a small dummy wrapper for things they want to use. I understand your dilemma, they only reason I suggested it is that this is for angular2 which is a proponent of these conventions. However I kind of a agree with you about how tenable this is. So I'll close this for now and maybe the angular community will pick something up that doesn't rely so heavily on a wrapper construct.
