### ISSUE TITLE
Can't create proper changelogs (c.)

### ISSUE THREAD

**Issue by CreativeZoller** [stevemao/gulp-conventional-changelog#3]
Continuing [this](https://github.com/conventional-changelog/conventional-changelog/issues/148) issue since it makes more sense, as I use gulp.
I tried out standard-version also. Still nothing additional knowledge from that readme. My changelog isn't modifying. If I check my repo history I have a bunch of commit messages, nicely done according to the commit convention guidelines. Still when I want to generate my changelog, tag, etc., I only see the same meaningless structure what I already copy-pasted before. So please be so kind as since it's your package, write me with an example how to modify my task to create the structure I'd like to see and as I also mentioned before on the other issue. Thanks.

**Comment by stevemao** [comment]
These packages are dog fooding themselves. How do I replicate your issue?

**Comment by CreativeZoller** [comment]
I made a test repo for this only. I included both standard version and the gulp version of conventional-changelog. Check and/or fork it [Here](https://github.com/CreativeZoller/changelog-test). Check my gulp task, check the changelog and my commit history. I do not understand how to create what I would like to with your packages so please show me the light at the end of the tunnel

**Comment by stevemao** [comment]
It's not "features" it's "feat"

**Comment by CreativeZoller** [comment]
Ah, thanks.
