### ISSUE TITLE
commit types not showing in changelog

### ISSUE THREAD

**Issue by CreativeZoller** [stevemao/gulp-conventional-changelog#4]
Okay now all my tasks are running but one big problem: only fix type commits are visible in my generated changelog file. So what is the proper way to activate the writing of `feat|fix|docs|style|refactor|test|chore` types to my changelog file?

**Comment by stevemao** [comment]
Hi @CreativeZoller , the issue tracker here is for bugs/features only. What you ask for is not a bug, and can be found in the [docs](https://github.com/conventional-changelog/standard-version/). Sorry but we have limited resources for support and we are actively looking for contributions.
